### ISSUE TITLE
Deaktivieren von - Running Hot... had to kill Queque! 

### ISSUE THREAD

**Issue by michi1996** [niciBume/Cat_Prey_Analyzer#15]
Meine Katzen fühlen sich sehr häufig, sehr wohl, vor der Katzenklappe. Das führt dazu das ich mit der Meldung "Running Hot... had to kill Queque!" zugespamt werde.

Braucht es diese Benachrichtigung überhaupt? Ich musste bisher nie etwas unternehmen und sobald sich die Katze aus dem staub gemacht hat hört es auch damit auf.

Gibt es eine Möglichkeit diese Meldung zu deaktivieren? Evtl. könnte man dies fix in den Telegram Bot implementieren?

**Comment by niciBume** [comment]
Mein Katzen auch...

Du kannst [diese line](https://github.com/niciBume/Cat_Prey_Analyzer/blob/a549d87368bb06491d6fa9843544dca5c43222b8/cascade.py#L320) auskommentieren um dies zu deaktivieren
