### ISSUE TITLE
Training Data

### ISSUE THREAD

**Issue by sventschui** [niciBume/Cat_Prey_Analyzer#17]
Hey there

Really cool writeup and experiments. I'm looking into doing something similar and have some ideas I want to try out. Is there a possibility to get hold of your training data?

Thanks & Best Regards

**Comment by niciBume** [comment]
Hey mate

What are you trying to do? As most data we used to train the model is openly available:

[Oxford Pets](https://www.robots.ox.ac.uk/~vgg/data/pets/)
[Kaggle Cat Face](https://www.kaggle.com/crawford/cat-dataset)

Cheers

**Comment by sventschui** [comment]
Thanks for the references! I'm also building a prey detection for my cat flap. But I want to play a bit with different algorithms/models (for educational purposes).

Would it be possible to share the prey images? Currently collecting my own data points but the more the better.

**Comment by niciBume** [comment]
Whats your e-mail? Then I can send you a Drive link. 
(I take the privacy of my cats seriously 😜)

**Comment by sventschui** [comment]
That sounds awesome! I'll respect the privacy of your cats and not share the data neither :) My mail is sventschui[at]gmail[dot]com Thanks a bunch in advance!
