### ISSUE TITLE
Submit Training Data

### ISSUE THREAD

**Issue by badsche** [niciBume/Cat_Prey_Analyzer#19]
Hi,
I've played around with the positioning of the camera because my cats seem to pass by too fast for the program to react. I overclocked the RPi4 to 2GHz and still don't get an image every time they pass by. I wonder if it would help when I provide some images (about 30, 2 with prey). 

Tank you!

Regards,
badsche

**Comment by niciBume** [comment]
Hey!
Sorry for the delayed reply. Currently I'm a bit swamped with work... but if you send me your mail I can add you to the google drive with the training images if you'd like to contribute :)
Regarding the inference speed, I suppose a TPU accelerator such as the google coral could help...

Cheers,
Nic

**Comment by badsche** [comment]
Ok, I'll try that Coral thing. 
My mail ist my username at gmail.com. You know what I mean. 

badsche

**Comment by badsche** [comment]
Perfect. I uploaded the images of my cats in a new folder. Sorry, there are the borders of the algorithm visible because I took the images from the Telegram chat. I hope that doesn't matter. 

badsche

**Comment by niciBume** [comment]
No worries. Thanks for contributing data (cute cat btw:)).
If you're further interested on the coral speedup I briefly mentioned it here: https://github.com/niciBume/Cat_Prey_Analyzer/issues/18#issuecomment-890515128

Nic
