### ISSUE TITLE
libmmal.so Picamera with bullseye

### ISSUE THREAD

**Issue by nscheur** [niciBume/Cat_Prey_Analyzer#20]
Hi I am trying to get your model under 64bit bullseye running, but Picamera is not part of bullseye anymore. so I get the error: 
OSError: libmmal.so: cannot open shared object file: No such file or directory

Do you know how I can adjust your model to get it running under Bullseye 64 bit?

I think it is a really cool project!

**Comment by niciBume** [comment]
Hey!
Sorry I'm not familiar with Bullseye. If you'd want to keep using the new OS you'd either have to wait until they update the picamera drivers or you use a different camera that runs with it, any UVC camera should do (I guess)?
If you go with the latter then you'll have to add some custom code to it, but tbh that's not really a big part of the code. Just add the image to the queue and it should work the same :)
