### ISSUE TITLE
cascade.py killed when Cat Detected

### ISSUE THREAD

**Issue by famascl3m** [niciBume/Cat_Prey_Analyzer#21]
hi i have the script running on a RPI 3 B (telegram working /sendlivepic)

when a Cat is detected the script kill himself instead of sending me a telegram message

`
Cat Detected!
Quelength: 4    Streamsize: 48
Haar_time:  0.49
Quelength: 5    Streamsize: 48
Quelength: 6    Streamsize: 48
Quelength: 7    Streamsize: 48
Quelength: 8    Streamsize: 48
Quelength: 9    Streamsize: 48
Killed`

**Comment by niciBume** [comment]
The Queue grew too large and the program killed itself to not get stuck.
RPI3 is quite a bit slower than RPI4 and not tested from my side... could be that the computation is too heavy for it to handle.

**Comment by famascl3m** [comment]
ok thanks i will change for a RPI4
