### ISSUE TITLE
Providing the training code and the cat images

### ISSUE THREAD

**Issue by jojowe** [niciBume/Cat_Prey_Analyzer#22]
Hi,
this project is my first approach to dive into in the ML-World.
So, first of all... Thank you for sharing your code.

Till now I set up the hardware, got everything running and collected my first cat images.

For a deeper understanding... Can you provide me with the code and the images to train the modell?

**Comment by niciBume** [comment]
Hey
Well it was my first project too, so I wouldn't advise you to learn from it... but if you pass me your mail I can give it to you.
Cheers

**Comment by jojowe** [comment]
Well, that's fine for me.
It gives me a practical project to work on alongside my theoretical courses.

dev.jojowe@gmail.com

thank you
