### ISSUE TITLE
Change camera settings for day and night mode

### ISSUE THREAD

**Issue by flaterne** [niciBume/Cat_Prey_Analyzer#23]
Hi niciBume,

this is a very interessting project and I am actualing trying to run this on my RasPi.
It works fine at daylight (I have not conntected the GPIO pins yet for the camera).
In your code I found the GPIO Pin 36 (IRPin), there you change the mode of the camera to night vision.
Is there an option to change between those two camera modes depending on the date time?
Or is this already included?
Sorry for the circumstances, I am new in learning python.
Thanks for your reply!

**Comment by niciBume** [comment]
I suppose that you could toggle the GPIO based on time, however this is not a built in option in this code base. You would need to write that piece of code and inject it approximately [here](https://github.com/niciBume/Cat_Prey_Analyzer/blob/master/camera_class.py#L34). But in general you can just leave it on, i.e. the camera works at night as well with this setting.
Never stop learning! :)

**Comment by flaterne** [comment]
great, thanks for the quick answer. I have connected the GPIO pin of the camera and the pictures are very good at day and night :)
