### ISSUE TITLE
Access to dataloader

### ISSUE THREAD

**Issue by famascl3m** [niciBume/Cat_Prey_Analyzer#24]
Hello,

Is it possible to have access to the dataloader you've used, because i would like to add my own picture 

Please 😃

**Comment by niciBume** [comment]
Hi @famascl3m 
I have it in a google drive and can share if you pass me you mail. It is quite terrible code however... 
If I may give a tip, with the rise of DALE2, you could try generating images with cats and prey, which was the main limitation back then, let me know if that method worked then!
Cheers

**Comment by famascl3m** [comment]
Thanks here is my mail : bouvret.clement@gmail.com

**Comment by niciBume** [comment]
done

**Comment by danielktaylor** [comment]
@niciBume can I also have access to the Google Drive folder, too? yoblin@gmail.com
