### ISSUE TITLE
Auch ein "Danke" muss mal sein! 

### ISSUE THREAD

**Issue by En3myNightmare** [niciBume/Cat_Prey_Analyzer#25]
Kein Problem, sondern nur ein kleines Dankeschön :-) 
Löst bei uns ein großes Problem, da unser Kater mittlerweile es sich zur Gewohnheit gemacht hat und seine toten Mäuse direkt vor unser Bett gelegt hat. War immer eine schöne Überraschung am Morgen. 

Anstatt über Telegram gehe ich via MQTT direkt an meinen HomeAssistant Server, welcher dann wireless die smarte Katzenklappe "SureFlap" steuert. Funktioniert tadellos. 

Also: Vielen Dank! 👍

**Comment by niciBume** [comment]
Vielen Dank für das Feedback! Freut mich zu hören dass dir das Project was bringt und den Kater in Schach haltet :)
