### ISSUE TITLE
System Killed

### ISSUE THREAD

**Issue by davidfrei90** [niciBume/Cat_Prey_Analyzer#7]
Hallo Nic

Ich bin es nocheinmal. Bin jetzt um einiges weiter gekommen. Danke nochmals
Das Program läuft (bekomme auch die Start Message vom Bot) aber nach kurzer Zeit stirbt das Program (nach ca. 1 Minute).
![grafik](https://user-images.githubusercontent.com/71548496/94863003-101ecb80-043a-11eb-8927-c1ec5dff338d.png)

Kann das an der Einstellung der Kamera liegen?
Oder hast du sonst eine Idee?
Danke
Gruss
David

**Comment by niciBume** [comment]
Kein Ding!
Ich glaube nicht dass es an der Kamera liegt, zur überprüfung kannst du mal ein Bild aus der Queue abspeichern und schauen wie das Bild aussieht. Dafür ändere die Funktion feed() auf Zeile 380 in cascade.py ab:
````
def feed(self, target_img, img_name):
        target_event_obj = Event_Element(img_name=img_name, cc_target_img=target_img)
        cv2.imwrite('debug_image.jpg', target_img)

        start_time = time.time()
        single_cascade = self.base_cascade.do_single_cascade(event_img_object=target_event_obj)
        single_cascade.total_inference_time = sum(filter(None, [
            single_cascade.cc_inference_time,
            single_cascade.cr_inference_time,
            single_cascade.bbs_inference_time,
            single_cascade.haar_inference_time,
            single_cascade.ff_bbs_inference_time,
            single_cascade.ff_haar_inference_time,
            single_cascade.pc_inference_time]))
        total_runtime = time.time() - start_time
        print('Total Runtime:', total_runtime)

        return total_runtime, single_cascade
````

Jetzt solltest du irgendwo im Ordner ein Bild namens debug_image.jpg haben, schau mal ob es "normal" aussieht, falls ja, ist die Kamera in Ordnung. 

Aber es scheint mir als würde die Cascade nicht durchlaufen werden => dass das Programm bei der Bearbeitung des ersten Bilds abstürzt. Du solltest in `/logs` ein `.csv` logfile haben, kannst du mir die letzten paar Zeilen davon zeigen? Hast du schonmal ein 'bearbeitetes' Bild vom Telegram Bot erhalten? Evt. könnte sich hier die Leistungsbarriere des RPI3 zeigen,  denn das RPI4 mit deutlich mehr Leistung läuft hier am Limit 😜

**Comment by davidfrei90** [comment]
Ich hab mir jetzt ein RPI4 gekauft und siehe da, es läuft.:)
Ich muss nur noch die Bilder automatisch speichern auf ein Server/Festplatte.
Dann kann ich mal über einen längeren Zeitraum Daten sammeln.
Ich danke dir für die Hilfe. Wir bleiben in Kontakt, falls es was neues gibt 👍

**Comment by niciBume** [comment]
Alles Klar! In dem Fall viel Spas damit! 👍
